/**
 * `scripts/check-memory.mjs`: the deterministic half of plan section 10.2's renderer
 * memory gate, and an honest account of the half that is not deterministic.
 *
 * ## Why this file exists
 *
 * Plan line 4198 lists `npm run check:memory` in Phase 9's verification block, and no
 * such script existed: `grep check:memory package.json` returned nothing. The phase was
 * unbuildable as written. This file covers the script that closes that gap.
 *
 * ## The honesty half
 *
 * Plan section 10.2 asks for "no material canvas or GPU memory growth over 20 world
 * mount and unmount cycles". That is a runtime property and cannot be read out of a
 * directory of files. So the assertions here are split in two, and both halves are
 * pinned:
 *
 * - The measurements the script *can* make - no eager Pixi chunk in the entry
 *   document, plan section 10.2's 800 KiB gzip ceiling for any lazy chunk, a
 *   coherent artifact, a non-vacuous run - are exercised against synthetic trees, so
 *   each one is shown to fail on a tree that violates it and pass on one that does not.
 * - The measurements it *cannot* make are asserted as an explicit, printed statement,
 *   so a reader of a green run cannot mistake this preflight for a leak measurement.
 *
 * The second half is the part worth defending. A build-level check dressed as a
 * memory check is worse than no check, because it is read as coverage. `NOT MEASURED`
 * is asserted to be non-empty, to name canvas count, GPU memory, heap, and context
 * loss, and to be printed on every run including the passing one.
 *
 * ## Hermeticity
 *
 * Every fixture is a synthetic `dist` written into a temp directory outside the
 * repository and passed with `--dist=`, so nothing here depends on a build having run,
 * on the checkout's history, or on where the checkout lives on disk. The same bytes
 * measured from two different working directories must produce two identical reports,
 * which is the Phase 8 defect this repo has already paid for once.
 *
 * Privacy: the fixtures contain generated bytes and a hand-written HTML document. No
 * subject, note, attachment, progression, statistic, or preference appears in any of
 * them, and nothing here writes inside the repository.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import {
  collectInitialAssets,
  evaluateMemoryPreflight,
  gzipSize,
  isDeclaredRendererFamily,
  LAZY_CHUNK_GZIP_BYTES,
  LAZY_CHUNK_GZIP_KIB,
  MOUNT_UNMOUNT_CYCLES,
  NOT_MEASURED,
  RENDERER_CHUNK_FAMILIES,
  RENDERER_FAMILY_NAMES,
  rendererChunkFamily,
  resolveInitialPath,
} from '../../scripts/check-memory.mjs';

import {
  cleanupScratch,
  entryHtml,
  filler,
  gzipSize as fixtureGzipSize,
  incompressible,
  REPO_ROOT,
  runNode,
  scratch,
  sourceOf,
  writeSyntheticDist,
} from './support/phase9Build';

afterAll(cleanupScratch);

const ENFORCER = path.join(REPO_ROOT, 'scripts', 'check-memory.mjs');
const enforcerSource = sourceOf('scripts/check-memory.mjs');

/** ~200 KiB of incompressible bytes: a chunk well under the ceiling, well over zero. */
const SMALL_RENDERER_BYTES = incompressible(200_000, 3);
/** ~900 KiB of incompressible bytes: over the 800 KiB gzip ceiling once gzipped. */
const HUGE_RENDERER_BYTES = incompressible(900_000, 5);

describe('the plan numbers are the ones the plan states', () => {
  it('pins the 800 KiB gzip lazy-chunk ceiling as integer bytes', () => {
    expect(LAZY_CHUNK_GZIP_BYTES).toBe(819_200);
    expect(LAZY_CHUNK_GZIP_KIB).toBe(800);
    expect(enforcerSource).toMatch(/LAZY_CHUNK_GZIP_BYTES\s*=\s*800 \* 1024/);
    expect(enforcerSource).toContain('Any lazy JavaScript chunk: no more than 800 KB gzip.');
    // The ceiling is otherwise unenforced: `check-bundle-size.mjs` allows 2.5 MB *raw*
    // per chunk, which is roughly 800 KB uncompressed, so today a renderer bundle
    // can reach twice the plan's gzip budget with no gate noticing.
    const bundleGuard = sourceOf('scripts/check-bundle-size.mjs');
    expect(bundleGuard).toContain('MAX_CHUNK_BYTES = 2_500_000');
  });

  it('records the plan section and the cycle count the browser lane will need', () => {
    expect(enforcerSource).toContain('plan section 10.2');
    expect(MOUNT_UNMOUNT_CYCLES).toBe(20);
    expect(enforcerSource).toMatch(/MOUNT_UNMOUNT_CYCLES\s*=\s*20/);
  });

  it('is deterministic: a stated gzip level, no clock, no randomness, no server', () => {
    expect(enforcerSource).toMatch(/GZIP_LEVEL\s*=\s*9/);
    expect(gzipSize(Buffer.from('a'.repeat(10_000), 'utf8'))).toBe(
      fixtureGzipSize(Buffer.from('a'.repeat(10_000), 'utf8')),
    );
    for (const forbidden of [/\bDate\b/, /Math\.random/, /localhost/, /createServer/, /127\.0\.0\.1/]) {
      expect(enforcerSource, String(forbidden)).not.toMatch(forbidden);
    }
    expect(enforcerSource).not.toMatch(/require\(/);
    const imports = [...enforcerSource.matchAll(/^import .* from '([^']+)';/gm)].map((match) => match[1]);
    expect(imports.length).toBeGreaterThan(0);
    for (const specifier of imports) expect(specifier, specifier).toMatch(/^node:/);
  });
});

describe('the entry document resolves to a set of initial files, and a dangling one is a problem', () => {
  it('collects module scripts, modulepreloads, and stylesheets once each', () => {
    const { initial, nomodule, problems } = collectInitialAssets(
      entryHtml({
        modules: ['index-a1.js', 'index-a1.js'],
        modulepreloads: ['vendor-react-b2.js', 'index-a1.js'],
        styles: ['index-c3.css'],
        nomodules: ['index-legacy-d4.js'],
      }),
    );
    expect(problems).toEqual([]);
    expect([...initial.keys()].sort()).toEqual([
      'assets/index-a1.js',
      'assets/index-c3.css',
      'assets/vendor-react-b2.js',
    ]);
    // Referenced by two kinds, counted once, and both kinds recorded.
    expect([...(initial.get('assets/index-a1.js')?.kinds ?? [])].sort()).toEqual([
      'js-module',
      'js-modulepreload',
    ]);
    // The ES5 fallback is collected separately, not folded into the initial set. It is
    // what a browser without module support downloads, and plan section 10.2 declines
    // to count it, so folding it in would report a finding in a browser the plan does
    // not support as if it were one in the browsers it does.
    expect([...nomodule.keys()]).toEqual(['assets/index-legacy-d4.js']);
    expect(nomodule.get('assets/index-legacy-d4.js')?.kinds).toEqual(['js-nomodule']);
  });

  it('does not treat a `nomodule` renderer chunk as an eager Pixi load', () => {
    const { initial, nomodule } = collectInitialAssets(
      entryHtml({ modules: ['index-a1.js'], nomodules: ['vendor-pixi-legacy-b2.js'] }),
    );
    const result = evaluateMemoryPreflight({
      chunks: [{ path: 'assets/vendor-pixi-legacy-b2.js', family: 'vendor-pixi', rawBytes: 10, gzipBytes: 10 }],
      assetsDirPresent: true,
      entryPaths: new Set(initial.keys()),
    });
    expect(nomodule.has('assets/vendor-pixi-legacy-b2.js')).toBe(true);
    expect(result.ok).toBe(true);
  });

  it('rejects a reference that leaves the artifact rather than counting it', () => {
    expect(resolveInitialPath('https://cdn.example.invalid/a.js')).toBeUndefined();
    expect(resolveInitialPath('//cdn.example.invalid/a.js')).toBeUndefined();
    expect(resolveInitialPath('/assets/../../etc/passwd')).toBeUndefined();
    expect(resolveInitialPath('/assets/index-a1.js?v=2')).toBe('assets/index-a1.js');
    const { problems } = collectInitialAssets(
      entryHtml({ remote: ['https://cdn.example.invalid/a.js'] }),
    );
    expect(problems).toHaveLength(1);
    expect(problems[0]).toContain('does not name a file inside the built artifact');
  });

  it('resolves a renderer family from the basename, never from a hash', () => {
    expect(rendererChunkFamily('assets/vendor-pixi-CkHy5qFN.js')).toBe('vendor-pixi');
    expect(rendererChunkFamily('assets/vendor-pixi-legacy-CD2.js')).toBe('vendor-pixi');
    expect(rendererChunkFamily('assets/vendor-phaser-BHvTOz-D.js')).toBe('vendor-phaser');
    expect(rendererChunkFamily('assets/index-CANyR14L.js')).toBeUndefined();
    expect(Object.keys(RENDERER_CHUNK_FAMILIES).sort()).toEqual(['vendor-phaser', 'vendor-pixi']);
  });
});

describe('the preflight decides pass or fail from a measurement', () => {
  const lazy = { path: 'assets/vendor-pixi-a1.js', family: 'vendor-pixi', rawBytes: 200_000, gzipBytes: 199_000 };

  it('passes a lazy Pixi chunk that is within the ceiling', () => {
    const result = evaluateMemoryPreflight({
      chunks: [lazy],
      assetsDirPresent: true,
      entryPaths: new Set(['assets/index-a1.js']),
    });
    expect(result.ok).toBe(true);
    expect(result.findings).toEqual([]);
    expect(result.byFamily['vendor-pixi'].eagerPaths).toEqual([]);
    expect(result.measuredCount).toBe(1);
  });

  it('fails an eager Pixi chunk, and says which chunk and which rule', () => {
    const result = evaluateMemoryPreflight({
      chunks: [lazy],
      assetsDirPresent: true,
      entryPaths: new Set(['assets/index-a1.js', 'assets/vendor-pixi-a1.js']),
    });
    expect(result.ok).toBe(false);
    expect(result.findings.map((finding) => finding.code)).toEqual(['eager-pixi']);
    expect(result.findings[0].message).toContain('assets/vendor-pixi-a1.js');
    expect(result.findings[0].message).toContain('Plan section 10.2');
  });

  it('reports an eager Phaser chunk without failing, because it is pre-existing and Phase 24 owns it', () => {
    const result = evaluateMemoryPreflight({
      chunks: [{ path: 'assets/vendor-phaser-b2.js', family: 'vendor-phaser', rawBytes: 10, gzipBytes: 10 }],
      assetsDirPresent: true,
      entryPaths: new Set(['assets/vendor-phaser-b2.js']),
    });
    expect(result.ok).toBe(true);
    expect(result.byFamily['vendor-phaser'].eagerPaths).toEqual(['assets/vendor-phaser-b2.js']);
  });

  it('fails a renderer chunk over the plan ceiling', () => {
    const result = evaluateMemoryPreflight({
      chunks: [{ path: 'assets/vendor-pixi-a1.js', family: 'vendor-pixi', rawBytes: 900_000, gzipBytes: LAZY_CHUNK_GZIP_BYTES + 1 }],
      assetsDirPresent: true,
      entryPaths: new Set(),
    });
    expect(result.ok).toBe(false);
    expect(result.findings.map((finding) => finding.code)).toEqual(['oversized-renderer']);
    expect(result.findings[0].message).toContain('800 KiB ceiling');
  });

  it('fails an artifact with no renderer chunk at all, rather than reporting nothing', () => {
    // The failure mode this gate exists to prevent, restated at the unit level: a
    // green run that measured nothing.
    const result = evaluateMemoryPreflight({
      chunks: [],
      assetsDirPresent: true,
      entryPaths: new Set(['assets/index-a1.js']),
    });
    expect(result.ok).toBe(false);
    expect(result.findings.map((finding) => finding.code)).toEqual(['no-renderer-chunk']);
  });

  it('fails an artifact with no assets tree at all', () => {
    const result = evaluateMemoryPreflight({ chunks: [], assetsDirPresent: false, entryPaths: new Set() });
    expect(result.ok).toBe(false);
    expect(result.findings.map((finding) => finding.code)).toEqual(['no-assets-tree']);
  });
});

describe('a family it does not know is a finding, not a TypeError', () => {
  it('reports an undeclared family and still returns a verdict', () => {
    // `MeasuredRendererChunk.family` is `string` in the declaration, so this input is
    // legal by the function's own types. The bug this holds shut was a `TypeError` at
    // `RENDERER_CHUNK_FAMILIES[family].renderer`, on the same line of code that
    // reports findings in sentence form - the gate contradicting its own stated rule
    // for the reader who needed the sentence.
    const result = evaluateMemoryPreflight({
      chunks: [
        { path: 'assets/vendor-mystery-a1.js', family: 'vendor-mystery', rawBytes: 10, gzipBytes: 10 },
      ],
      assetsDirPresent: true,
      entryPaths: new Set(),
    });
    expect(result.findings.map((finding) => finding.code)).toEqual(['unknown-renderer-family']);
    expect(result.findings[0].message).toContain('vendor-mystery');
    expect(result.findings[0].message).toContain('RENDERER_CHUNK_FAMILIES');
    expect(result.ok).toBe(false);
    // And the census still accounts for it, rather than dropping a measured chunk.
    expect(result.measuredCount).toBe(1);
    expect(result.byFamily['vendor-mystery'].renderer).toBe('vendor-mystery');
  });

  it('does not throw for any string, including the empty one and a prototype key', () => {
    // The two values a registry lookup most easily dies on: an empty string, and a
    // key that exists on `Object.prototype` and would be found by `in`.
    for (const family of ['', 'toString', 'constructor', 'vendor-pixi/../vendor-phaser', 'VENDOR-PIXI']) {
      const call = () =>
        evaluateMemoryPreflight({
          chunks: [{ path: 'assets/x-a1.js', family, rawBytes: 1, gzipBytes: 1 }],
          assetsDirPresent: true,
          entryPaths: new Set(),
        });
      expect(call, family).not.toThrow();
      expect(call().findings.map((finding) => finding.code), family).toContain('unknown-renderer-family');
    }
  });

  it('an inherited property is not a declared family, because a registry lookup must use hasOwnProperty', () => {
    expect(isDeclaredRendererFamily('vendor-pixi')).toBe(true);
    expect(isDeclaredRendererFamily('toString')).toBe(false);
    expect(isDeclaredRendererFamily('__proto__')).toBe(false);
  });

  it('the declaration is what the runtime consults, and every family carries both prose fields', () => {
    // If a family were added without an `absence` line, the report would print
    // `undefined` in the exact place that exists to keep a reader from mistaking
    // absence for a measurement.
    expect(RENDERER_FAMILY_NAMES).toEqual(Object.keys(RENDERER_CHUNK_FAMILIES));
    for (const family of RENDERER_FAMILY_NAMES) {
      const entry = RENDERER_CHUNK_FAMILIES[family];
      expect(entry.reason.length, `${family}.reason`).toBeGreaterThan(20);
      expect(entry.absence.length, `${family}.absence`).toBeGreaterThan(20);
    }
  });
});

describe('absence is reported per family, and never counted as a measurement', () => {
  const phaserOnly = {
    chunks: [{ path: 'assets/vendor-phaser-b2.js', family: 'vendor-phaser', rawBytes: 10, gzipBytes: 10 }],
    assetsDirPresent: true,
    entryPaths: new Set<string>(),
  };

  it('names the absent family, and says the Pixi verdict was not established here', () => {
    // The default production build. It passes, and it measured Phaser. It did not
    // measure Pixi, and the two states have to be distinguishable in the result and
    // not only in the prose.
    const result = evaluateMemoryPreflight(phaserOnly);
    expect(result.ok).toBe(true);
    expect(result.families).toEqual(['vendor-phaser']);
    expect(result.measuredFamilies).toEqual(['Phaser']);
    expect(result.absentFamilies).toEqual(['PixiJS']);
    expect(result.familiesReport.map((entry) => [entry.family, entry.present])).toEqual([
      ['vendor-phaser', true],
      ['vendor-pixi', false],
    ]);
    // An absent family is a reported fact, not a finding - otherwise the default
    // build could never pass its own gate.
    expect(result.findings).toEqual([]);
  });

  it('measures the family on the build that contains it, and the report is symmetric', () => {
    const pixiBuild = evaluateMemoryPreflight({
      chunks: [{ path: 'assets/vendor-pixi-b2.js', family: 'vendor-pixi', rawBytes: 10, gzipBytes: 10 }],
      assetsDirPresent: true,
      entryPaths: new Set(),
    });
    expect(pixiBuild.measuredFamilies).toEqual(['PixiJS']);
    expect(pixiBuild.absentFamilies).toEqual(['Phaser']);
    expect(pixiBuild.byFamily['vendor-pixi'].eagerPaths).toEqual([]);
  });

  it('a family with no chunk reports zero measurement and present: false, not a clean family', () => {
    const absent = evaluateMemoryPreflight({ chunks: [], assetsDirPresent: true, entryPaths: new Set() })
      .familiesReport.find((entry) => entry.family === 'vendor-pixi');
    expect(absent).toMatchObject({ present: false, chunks: [], rawBytes: 0, gzipBytes: 0, eagerPaths: [] });
  });

  it('the CLI prints the absence on the default build and enumerates the measured families on a pass', () => {
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'] },
      { 'index-a1.js': filler(2_000), 'vendor-phaser-b2.js': SMALL_RENDERER_BYTES },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code, run.output).toBe(0);
    expect(run.output).toContain('vendor-pixi (PixiJS) - NOT PRESENT in this build');
    expect(run.output).toContain('No PixiJS chunk in this artifact, so nothing about it was measured.');
    expect(run.output).toContain('Renderer families NOT measured on this artifact (absent from it, not clean): PixiJS');
    expect(run.output).toContain('Measured for eager load: Phaser.');
    expect(run.output).toContain('NOT measured on this artifact (absent from it, so not clean either): PixiJS');
    // The old closing sentence claimed the Pixi verdict for this artifact. It must
    // not be back: on a build with no Pixi chunk the claim is about the build.
    expect(run.output).not.toContain('2 renderer chunk(s) measured, no eager Pixi chunk, all within');
  });

  it('and the Pixi build measures Pixi rather than reporting its absence', () => {
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'] },
      { 'index-a1.js': filler(2_000), 'vendor-pixi-b2.js': SMALL_RENDERER_BYTES },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code, run.output).toBe(0);
    expect(run.output).toContain('vendor-pixi (PixiJS) - measured');
    expect(run.output).toContain('Measured for eager load: PixiJS.');
    expect(run.output).toContain('NOT measured on this artifact (absent from it, so not clean either): Phaser.');
    // The Pixi measurement is real here, and the report does not need to hedge it.
    expect(run.output).not.toContain('"no eager Pixi load on Welcome" is established on the');
  });
});

describe('the CLI can fail, and each failure is reachable from a synthetic tree', () => {
  it('fails rather than passing when there is no built entry document', () => {
    const missing = path.join(scratch(), 'no-such-dist');
    const run = runNode(ENFORCER, [`--dist=${missing}`]);
    expect(run.code).toBe(1);
    expect(run.output).toContain('no built entry document');
    // The specific divergence from check-bundle-size.mjs, which warns and exits 0 when
    // `dist` is absent.
    expect(sourceOf('scripts/check-bundle-size.mjs')).toContain('process.exit(0)');
    expect(run.output).toContain('Run: npm run build:web');
  });

  it('fails an entry document that names a renderer chunk the build does not contain', () => {
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'], modulepreloads: ['vendor-pixi-missing.js'] },
      { 'index-a1.js': filler(2_000) },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code).toBe(1);
    expect(run.output).toContain('names a renderer chunk the build does not contain');
    expect(run.output).toContain('vendor-pixi-missing.js');
  });

  it('fails an eager Pixi chunk and passes the same tree once the chunk is lazy', () => {
    const eager = writeSyntheticDist(
      {
        modules: ['index-a1.js'],
        modulepreloads: ['vendor-pixi-b2.js', 'vendor-phaser-c3.js'],
      },
      {
        'index-a1.js': filler(20_000),
        'vendor-pixi-b2.js': SMALL_RENDERER_BYTES,
        'vendor-phaser-c3.js': SMALL_RENDERER_BYTES,
      },
    );
    const eagerRun = runNode(ENFORCER, [`--dist=${eager}`]);
    expect(eagerRun.code).toBe(1);
    expect(eagerRun.output).toContain('[eager-pixi]');
    expect(eagerRun.output).toContain('vendor-pixi-b2.js');
    // The Phaser chunk in the same tree is named by the entry document and reported,
    // and it is not what failed the run.
    expect(eagerRun.output).toContain('named by the entry document');

    const lazy = writeSyntheticDist(
      { modules: ['index-a1.js'], modulepreloads: ['vendor-phaser-c3.js'] },
      {
        'index-a1.js': filler(20_000),
        'vendor-pixi-b2.js': SMALL_RENDERER_BYTES,
        'vendor-phaser-c3.js': SMALL_RENDERER_BYTES,
      },
    );
    const lazyRun = runNode(ENFORCER, [`--dist=${lazy}`]);
    expect(lazyRun.code, lazyRun.output).toBe(0);
    expect(lazyRun.output).toContain('lazy');
    expect(lazyRun.output).toContain('vendor-pixi-b2.js');
  });

  it('fails a renderer chunk over the plan ceiling', () => {
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'] },
      { 'index-a1.js': filler(2_000), 'vendor-pixi-big.js': HUGE_RENDERER_BYTES },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code).toBe(1);
    expect(run.output).toContain('[oversized-renderer]');
    expect(run.output).toContain('800 KiB ceiling');
  });

  it('fails an artifact with no renderer chunk, rather than reporting a pass', () => {
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'] },
      { 'index-a1.js': filler(2_000) },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code).toBe(1);
    expect(run.output).toContain('[no-renderer-chunk]');
  });

  it('fails an artifact whose assets tree is missing', () => {
    const dist = scratch();
    mkdirSync(dist, { recursive: true });
    writeFileSync(path.join(dist, 'index.html'), entryHtml({ modules: ['index-a1.js'] }), 'utf8');
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code).toBe(1);
    expect(run.output).toContain('[no-assets-tree]');
  });
});

describe('the report says what it did not measure, on every run including the passing one', () => {
  it('names the properties that need a browser, and prints them on a pass', () => {
    expect(NOT_MEASURED.length).toBeGreaterThanOrEqual(4);
    const named = NOT_MEASURED.map((item) => item.property).join(' | ');
    expect(named).toContain('canvas count');
    expect(named).toContain('GPU texture and buffer memory growth');
    expect(named).toContain('JavaScript heap growth');
    expect(named).toContain('context loss');
    for (const item of NOT_MEASURED) {
      expect(item.needs.length, item.property).toBeGreaterThan(20);
      expect(item.needs, item.property).toMatch(/lane/i);
    }

    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'] },
      { 'index-a1.js': filler(2_000), 'vendor-pixi-a1.js': SMALL_RENDERER_BYTES },
    );
    const run = runNode(ENFORCER, [`--dist=${dist}`]);
    expect(run.code).toBe(0);
    expect(run.output).toContain('NOT MEASURED HERE');
    expect(run.output).toContain('canvas count over 20 world mount/unmount cycles');
    expect(run.output).toContain('is not established by this run');
    expect(run.output).toContain('It is not a mount/unmount leak measurement.');
  });

  it('names the properties in its header, before anyone reaches the CLI output', () => {
    expect(enforcerSource).toContain('What this script CANNOT prove, and will not claim');
    expect(enforcerSource).toContain('Nothing in this file, and no line of its');
    expect(enforcerSource).toMatch(/marker search over minified output was considered and rejected/i);
  });
});

describe('the report does not depend on where the checkout lives, or on a build having run', () => {
  it('produces the same report from two different working directories', () => {
    // The Phase 8 defect: one test's path-stripping regex matched only an absolute
    // `/tmp` path, so it had only ever been exercised from a tree under `/tmp`. Here
    // the same bytes are measured once from the repository root and once from a
    // scratch root that is not the repository, and the reports must be identical
    // without any post-processing at all.
    const dist = writeSyntheticDist(
      { modules: ['index-a1.js'], modulepreloads: ['vendor-phaser-b2.js'] },
      { 'index-a1.js': filler(20_000), 'vendor-phaser-b2.js': SMALL_RENDERER_BYTES },
    );
    const fromRepo = runNode(ENFORCER, [`--dist=${dist}`]);
    const elsewhere = scratch();
    // `--dist` is resolved against the script's own root, as
    // `scripts/check-welcome-budget.mjs` documents, so the relative form is computed
    // against the repository and the working directory is somewhere else entirely.
    const byRelative = runNode(ENFORCER, [`--dist=${path.relative(REPO_ROOT, dist)}`], elsewhere);

    expect(fromRepo.code, fromRepo.output).toBe(0);
    expect(byRelative.code, byRelative.output).toBe(0);
    expect(byRelative.output).toBe(fromRepo.output);
  });

  it('produces genuinely incompressible fixtures, so the size ceiling can bind', () => {
    // The control for the fixture generator. A 900 000-byte "random" buffer that
    // gzips to under 4 KiB makes `oversized-renderer` unreachable and the ceiling
    // looks enforced while never binding, which is the same class of defect as a gate
    // that passes because it measured nothing.
    const ratio = fixtureGzipSize(HUGE_RENDERER_BYTES) / HUGE_RENDERER_BYTES.length;
    expect(ratio).toBeGreaterThan(0.9);
    expect(fixtureGzipSize(HUGE_RENDERER_BYTES)).toBeGreaterThan(LAZY_CHUNK_GZIP_BYTES);
    expect(fixtureGzipSize(SMALL_RENDERER_BYTES)).toBeLessThan(LAZY_CHUNK_GZIP_BYTES);
  });

  it('builds no fixture inside the repository', () => {
    // The support helper's scratch roots are under the OS temp dir; a fixture that
    // wrote into `dist/` would make the suite depend on a build having run.
    expect(scratch().startsWith(REPO_ROOT)).toBe(false);
  });
});
