/**
 * Sprite manifest service.
 *
 * Provides type definitions and fetch/validation for the sprite manifest
 * generated by `scripts/generate-sprite-manifest.mjs`.
 */
import { isElectronAvailable } from '@/services/electronBridge';

export interface ManifestSprite {
  path: string;
  name: string;
  category: string;
  width: number;
  height: number;
}

export interface SpriteManifest {
  generatedAt: string;
  totalSprites: number;
  sprites: ManifestSprite[];
}

const BASE = import.meta.env.BASE_URL;
const MANIFEST_URL = `${BASE}assets/sprite-manifest.json`;

function isManifest(obj: unknown): obj is SpriteManifest {
  if (!obj || typeof obj !== 'object') return false;
  const m = obj as Record<string, unknown>;
  return (
    typeof m.generatedAt === 'string' &&
    typeof m.totalSprites === 'number' &&
    Array.isArray(m.sprites) &&
    m.sprites.every(
      (s: unknown) =>
        s !== null &&
        typeof s === 'object' &&
        typeof (s as Record<string, unknown>).path === 'string' &&
        typeof (s as Record<string, unknown>).name === 'string' &&
        typeof (s as Record<string, unknown>).category === 'string' &&
        typeof (s as Record<string, unknown>).width === 'number' &&
        typeof (s as Record<string, unknown>).height === 'number',
    )
  );
}

/**
 * Fetch the sprite manifest. In Electron, uses IPC bridge to get it from
 * the main process filesystem. In web, fetches from the static URL.
 */
export async function fetchSpriteManifest(): Promise<SpriteManifest> {
  if (isElectronAvailable()) {
    const bridge = window.electronKnowledgeBridge;
    if (bridge && typeof bridge.getSpriteManifest === 'function') {
      const raw = await bridge.getSpriteManifest();
      if (isManifest(raw)) return raw;
      throw new Error('Invalid sprite manifest from Electron bridge');
    }
    throw new Error('Electron bridge does not support getSpriteManifest');
  }

  const response = await fetch(MANIFEST_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch sprite manifest: ${response.status}`);
  }
  const json: unknown = await response.json();
  if (!isManifest(json)) {
    throw new Error('Invalid sprite manifest format');
  }
  return json;
}

/**
 * Look up a manifest sprite definition by its relative path.
 */
export function findSprite(
  manifest: SpriteManifest,
  path: string,
): ManifestSprite | undefined {
  return manifest.sprites.find((s) => s.path === path);
}

/**
 * Categorised grouping of sprites for the browser UI.
 */
export interface CategoryGroup {
  category: string;
  sprites: ManifestSprite[];
}

export function groupByCategory(manifest: SpriteManifest): CategoryGroup[] {
  const groups = new Map<string, ManifestSprite[]>();
  for (const sprite of manifest.sprites) {
    const existing = groups.get(sprite.category);
    if (existing) {
      existing.push(sprite);
    } else {
      groups.set(sprite.category, [sprite]);
    }
  }
  return Array.from(groups.entries())
    .map(([category, sprites]) => ({ category, sprites }))
    .sort((a, b) => a.category.localeCompare(b.category));
}
