/**
 * Independent verification of the Phase 8 gates, by the QA engineer.
 *
 * The Phase 8 suite already has a lot of coverage. This file deliberately does
 * not duplicate it. It covers the properties an independent pass found were
 * *asserted nowhere*, and it does so by reading the real artifacts and by
 * running the real scripts, so a green result here is a measurement rather than a
 * restatement of the implementation's own opinion of itself.
 *
 * What is here, and why each piece was not already covered:
 *
 * 1. **The remote-font gate can fail.** `currentBuild.spec.ts` recorded the
 *    recognised legacy font requests and asserted nothing about them, so Phase
 *    8's "the app renders without remote font requests" had no failing state.
 *    The predicate now lives in `./support/remoteFontGate.ts` and this file is
 *    its negative control: the same exported function is fed a synthetic request
 *    and must throw, with a message that names no hostname. The text assertions
 *    afterwards prove the spec actually calls it, so the control cannot pass
 *    vacuously against a spec that stopped using it.
 *
 * 2. **The media and budget gates are not behind the Cozy flag.** Both are
 *    project-level gates. If either read `VITE_COZY_VISUALS`, rolling the flag
 *    off would switch the gate off with it - the one thing a licensing gate and a
 *    performance budget must never share a switch with. This file asserts the
 *    flag is absent from both scripts *and* runs each of them with the flag set
 *    to `true` and to `false` and requires identical outcomes.
 *
 * 3. **The published registry cannot carry learner data.** It is served
 *    publicly at `/assets/asset-licenses.json`. A closed key vocabulary plus a
 *    scan of every string value is the cheapest honest check: an unknown key
 *    fails, and so does anything shaped like a subject name, a note, a room
 *    identifier, an email address, or a UUID.
 *
 * 4. **The built artifact carries no remote font and no remote origin.** Read
 *    from `dist/`, not from source, because source is not what ships. The
 *    generated Cozy stylesheet is checked for the same two things, since it is
 *    checked into the tree and would survive a build that stopped importing it.
 *
 * 5. **The rollback is a rollback.** The three legacy theme blocks must be
 *    byte-identical to their pre-Phase-8 values, and the only change permitted in
 *    `:root` is the three font-stack lines the no-remote-font criterion requires.
 *    The "before" comes from a committed baseline fixture with its own re-derived
 *    digest, not from the checkout's history: `git show HEAD:src/styles.css` made
 *    the gate compare the stylesheet against itself the moment the change was
 *    committed, so it passed in a dirty working tree and failed in a checkout of
 *    the committed state. The 5,813 lines below the theme blocks are held to the
 *    same standard by a pinned digest of the pre-Phase-8 region, so "unchanged" is
 *    a fact about bytes rather than a claim about what a runner happened to fetch.
 *
 * 6. **The recorded media-extension set is pinned.** The CC0 checker's media list
 *    is what makes "new media cannot be added without CC0 metadata" a mechanical
 *    rule, and it is the set an unlisted suffix can slip past. Pinning the set
 *    means a future edit to it is a reviewed act rather than a quiet widening.
 *    See the known-gap note in this file's tail for what pinning does *not* fix.
 *
 * 7. **The six Cozy placeholders are genuinely procedural.** They are admitted to
 *    the `pixi-default` bundle on the strength of being generated by a committed
 *    script, so the generator is run in a scratch tree and its output compared
 *    byte-for-byte with what is committed, and run twice to confirm it is
 *    deterministic. A generator that does not reproduce its own output is a
 *    provenance claim with nothing under it, and the pinned SHA-256s would then
 *    be pinning an arbitrary file.
 *
 * Privacy: this file contains no learner data, makes no network request, and
 * spawns only `node` against the repository and scratch directories under the OS
 * temp dir. It reads no commit history, and it never writes to `public/`, `src/`,
 * `scripts/`, or `dist/`.
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterAll, describe, expect, it } from 'vitest';

import {
  assertNoRemoteFontRequests,
  countRemoteFontRequests,
  remoteFontRequestsFailureMessage,
} from './support/remoteFontGate';

const REPO_ROOT = process.cwd();
const SPEC_PATH = path.join(REPO_ROOT, 'tests', 'e2e', 'currentBuild.spec.ts');
const GATE_PATH = path.join(REPO_ROOT, 'tests', 'phase8', 'support', 'remoteFontGate.ts');
const CC0_CHECKER_PATH = path.join(REPO_ROOT, 'scripts', 'check-cc0-assets.mjs');
const BUDGET_SCRIPT_PATH = path.join(REPO_ROOT, 'scripts', 'check-welcome-budget.mjs');
const GENERATOR_PATH = path.join(REPO_ROOT, 'scripts', 'generate-cozy-placeholders.mjs');
const REGISTRY_PATH = path.join(REPO_ROOT, 'public', 'assets', 'asset-licenses.json');
const CREDITS_PATH = path.join(REPO_ROOT, 'public', 'assets', 'CREDITS.md');
const COZY_TOKENS_CSS = path.join(REPO_ROOT, 'src', 'styles', 'cozy-tokens.css');
const COZY_CSS = path.join(REPO_ROOT, 'src', 'styles', 'cozy.css');
const STYLES_PATH = path.join(REPO_ROOT, 'src', 'styles.css');
const DIST = path.join(REPO_ROOT, 'dist');
const COZY_DIR = path.join(REPO_ROOT, 'public', 'assets', 'cozy');
const KNOWN_LEGACY_FONT_HOST_COUNT = 2;

const specSource = readFileSync(SPEC_PATH, 'utf8');
const gateSource = readFileSync(GATE_PATH, 'utf8');
const cc0CheckerSource = readFileSync(CC0_CHECKER_PATH, 'utf8');
const budgetSource = readFileSync(BUDGET_SCRIPT_PATH, 'utf8');

/** Scratch roots created during the run, removed in `afterAll`. */
const scratchRoots: string[] = [];
function scratch(prefix: string): string {
  const root = mkdtempSync(path.join(tmpdir(), `kd-phase8-qa-${prefix}-`));
  scratchRoots.push(root);
  return root;
}
afterAll(() => {
  for (const root of scratchRoots) rmSync(root, { recursive: true, force: true });
});

/* ========================================================================== */
/* 1. The remote-font gate is bound, and it can fail.                          */
/* ========================================================================== */

describe('the remote-font gate has a failing state', () => {
  it('passes on an empty request list, which is what the default artifact must produce', () => {
    expect(countRemoteFontRequests([])).toBe(0);
    expect(() => assertNoRemoteFontRequests([])).not.toThrow();
  });

  it('FAILS when a recognised legacy font request is present - the negative control', () => {
    // The same exported function the Playwright test calls. If this does not
    // throw, the shipped assertion cannot fail either, and Phase 8's exit
    // criterion is theatre.
    const observed = [
      { resourceType: 'stylesheet', method: 'GET', url: 'https://fonts.googleapis.invalid/css2' },
      { resourceType: 'font', method: 'GET', url: 'https://fonts.gstatic.invalid/x.woff2' },
    ];
    expect(countRemoteFontRequests(observed)).toBe(2);
    expect(() => assertNoRemoteFontRequests(observed)).toThrow(
      /2 request\(s\) reached a recognised legacy static font host/,
    );
  });

  it('fails for a single request too, so there is no small count that slips through', () => {
    expect(() => assertNoRemoteFontRequests([{ resourceType: 'stylesheet' }])).toThrow();
  });

  it('names the plan criterion in the failure, so the red run says what broke', () => {
    const message = remoteFontRequestsFailureMessage([{ resourceType: 'font' }]);
    expect(message).toContain('Plan section 10.2');
    expect(message).toContain('must be zero');
    expect(message).toContain('font');
  });

  it('prints no hostname and no path, in the failure or in the exported helpers', () => {
    const observed = [
      { resourceType: 'stylesheet', url: 'https://fonts.googleapis.invalid/css2?family=Cinzel' },
    ];
    const message = remoteFontRequestsFailureMessage(observed);
    // A hostname, a path, and a query each have to be absent: the privacy suite
    // exists to prove there is no destination, so a failing run must not print one.
    expect(message).not.toMatch(/fonts\.(googleapis|gstatic)/);
    expect(message).not.toMatch(/https?:\/\//);
    expect(message).not.toContain('css2');
    expect(message).not.toContain('Cinzel');
    // And the module must not be able to reach a destination in the first place.
    expect(gateSource).not.toMatch(/new URL\(/);
    expect(gateSource).not.toMatch(/\.hostname/);
  });

  it('the Playwright spec actually applies the shipped predicate to the recorded requests', () => {
    // Text, not execution: the spec cannot be imported into vitest without
    // registering Playwright tests. Reading it is the same technique
    // `welcome-narrow-viewport.test.ts` uses, and it is what stops this control
    // from passing against a spec that kept recording the list but stopped
    // asserting on it.
    expect(specSource).toContain("from '../phase8/support/remoteFontGate'");
    expect(specSource).toContain('assertNoRemoteFontRequests');
    // Applied to the tolerance list, not to something derived: the assertion has
    // to be about exactly the requests the privacy spy chose not to report.
    expect(specSource).toMatch(
      /assertNoRemoteFontRequests\(\s*privacyReport\.blockedLegacyFontRequests/,
    );
    // The count is recorded before the assertion, so a red run still says how many.
    expect(specSource).toMatch(
      /countRemoteFontRequests\(\s*privacyReport\.blockedLegacyFontRequests/,
    );
    expect(specSource.indexOf('remoteFontRequestCount')).toBeLessThan(
      specSource.indexOf('assertNoRemoteFontRequests(privacyReport'),
    );
  });

  it('keeps the known-legacy tolerance, so a regression fails readably rather than anonymously', () => {
    // The tolerance is the reason the gate can name a font host at all. Removing
    // it would turn a reintroduced font import into an anonymous external-
    // destination failure in a suite premised on there being no external traffic.
    for (const host of ['fonts.googleapis.com', 'fonts.gstatic.com']) {
      expect(specSource, host).toContain(`'${host}'`);
    }
    const recognised = /knownLegacyFontHosts\s*=\s*new Set\(\[([^\]]*)\]\)/.exec(specSource)?.[1] ?? '';
    expect(recognised.split(',').filter((entry) => entry.trim().length > 0)).toHaveLength(
      KNOWN_LEGACY_FONT_HOST_COUNT,
    );
    expect(specSource).toContain('blockedLegacyFontRequests.push(observation)');
    // And the tolerance is not the whole privacy check: an unrecognised external
    // host is still a violation. The `else` is asserted rather than assumed,
    // because a tolerance with no fallback branch is a hole, not a gate.
    const toleranceBranch = /knownLegacyFontHosts\.has\(url\.hostname\)[\s\S]{0,220}?else\s*\{[\s\S]{0,220}?violations\.push/.exec(
      specSource,
    );
    expect(toleranceBranch, 'the known-legacy branch has no violation fallback').not.toBeNull();
  });
});

/* ========================================================================== */
/* 2. Neither project-level gate is behind the Cozy flag.                      */
/* ========================================================================== */

describe('the media and budget gates are not gated behind VITE_COZY_VISUALS', () => {
  it('neither script mentions the flag, the runtime config, or the theme modules', () => {
    for (const [name, source] of [
      ['check-cc0-assets.mjs', cc0CheckerSource],
      ['check-welcome-budget.mjs', budgetSource],
    ] as const) {
      for (const forbidden of [
        'VITE_COZY_VISUALS',
        'cozyVisuals',
        'runtimeConfig',
        'import.meta.env',
        'src/theme',
      ]) {
        expect(source, `${name} mentions ${forbidden}`).not.toContain(forbidden);
      }
      // They read files, so the only runtime dependency they may have is Node.
      const specifiers = [...source.matchAll(/^import .* from '([^']+)';/gm)].map((m) => m[1]);
      expect(specifiers.length, name).toBeGreaterThan(0);
      for (const specifier of specifiers) expect(specifier, `${name}: ${specifier}`).toMatch(/^node:/);
    }
  });

  it('the media gate behaves identically with the flag on and off', () => {
    // Run for real, both ways, against a copy of the tree in a scratch directory,
    // so the comparison cannot be satisfied by the script merely ignoring the
    // variable - it has to produce the same verdict either way.
    const root = scratch('flag');
    const assets = path.join(root, 'public', 'assets');
    mkdirSync(path.join(root, 'scripts'), { recursive: true });
    cpSync(CC0_CHECKER_PATH, path.join(root, 'scripts', 'check-cc0-assets.mjs'));
    cpSync(GENERATOR_PATH, path.join(root, 'scripts', 'generate-cozy-placeholders.mjs'));
    cpSync(
      path.join(REPO_ROOT, 'scripts', 'generate-sprite-manifest.mjs'),
      path.join(root, 'scripts', 'generate-sprite-manifest.mjs'),
    );
    cpSync(path.join(REPO_ROOT, 'public', 'assets'), assets, { recursive: true });

    const run = (flag: string) => {
      try {
        const stdout = execFileSync(process.execPath, [CC0_CHECKER_PATH], {
          cwd: REPO_ROOT,
          encoding: 'utf8',
          stdio: ['ignore', 'pipe', 'pipe'],
          env: { ...process.env, VITE_COZY_VISUALS: flag },
        });
        return { exit: 0, stdout };
      } catch (error) {
        const failure = error as { status?: number; stdout?: string; stderr?: string };
        return { exit: failure.status ?? -1, stdout: `${failure.stdout ?? ''}${failure.stderr ?? ''}` };
      }
    };

    const on = run('true');
    const off = run('false');
    expect(on.exit, on.stdout).toBe(0);
    expect(off.exit, off.stdout).toBe(0);
    // Identical verdicts, not merely identical exit codes: the summary is the
    // claim being made, so it has to be the same claim in both flag states.
    expect(on.stdout).toBe(off.stdout);
  });

  it('the Welcome budget gate behaves identically with the flag on and off', () => {
    // `dist` is not committed, so a missing build is the honest input here: the
    // point is that the two flag states take the same path and reach the same
    // verdict, and the budget gate is written to fail rather than pass an
    // unmeasured build. When a build *is* present, the run is compared instead.
    const run = (flag: string) => {
      try {
        const stdout = execFileSync(process.execPath, [BUDGET_SCRIPT_PATH], {
          cwd: REPO_ROOT,
          encoding: 'utf8',
          stdio: ['ignore', 'pipe', 'pipe'],
          env: { ...process.env, VITE_COZY_VISUALS: flag },
        });
        return { exit: 0, stdout: `${stdout}` };
      } catch (error) {
        const failure = error as { status?: number; stdout?: string; stderr?: string };
        return { exit: failure.status ?? -1, stdout: `${failure.stdout ?? ''}${failure.stderr ?? ''}` };
      }
    };
    const on = run('true');
    const off = run('false');
    expect(on.exit, on.stdout).toBe(off.exit);
    expect(on.stdout).toBe(off.stdout);
  });
});

/* ========================================================================== */
/* 3. The published registry carries no learner data.                          */
/* ========================================================================== */

interface RegistryEntry {
  id?: unknown;
  path?: unknown;
  classification?: unknown;
  media?: unknown;
  [key: string]: unknown;
}
interface Registry {
  [key: string]: unknown;
  assets?: RegistryEntry[];
}

describe('the publicly served media registry carries no learner data', () => {
  const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')) as Registry;
  const entries = registry.assets ?? [];

  it('is registered as a non-media repository file, so it is not a Pixi bundle member', () => {
    const self = entries.filter((entry) => entry.path === 'public/assets/asset-licenses.json');
    expect(self).toHaveLength(1);
    expect(self[0].classification).toBe('repository-authored');
    expect(self[0].media).toBe(false);
    expect(self[0].bundles).toEqual([]);
    expect(self[0].pixiEligible).toBe(false);
  });

  it('uses a closed key vocabulary: paths, ids, license facts, checksums, commit shas', () => {
    // The vocabulary the checker declares is the vocabulary that is allowed. An
    // unknown key is how a field that has nothing to do with licensing would
    // arrive, and nothing else in the gate would notice.
    const allowedEntryKeys = new Set([
      'id', 'path', 'classification', 'media', 'title', 'role', 'notes',
      'license', 'licenseVerified', 'licenseUrl', 'licenseUnverifiedReason',
      'creator', 'source', 'sourceUrl', 'sourceUrlNotApplicable',
      'date', 'dateKind', 'sha256', 'checksumPolicy', 'generation',
      'modifications', 'introducedBy', 'modifiedBy', 'bundles', 'pixiEligible',
      'legacyRenderer', 'retention',
    ]);
    const allowedGenerationKeys = new Set([
      'script', 'command', 'recipe', 'embedMarker', 'semanticCheck', 'checksum',
    ]);
    const allowedCommitKeys = new Set(['commit', 'date', 'subject']);
    const allowedSourceUrlKeys = new Set(['reason']);

    for (const entry of entries) {
      for (const key of Object.keys(entry)) {
        expect(allowedEntryKeys.has(key), `entry ${String(entry.id)} has key "${key}"`).toBe(true);
      }
      const generation = entry.generation as Record<string, unknown> | undefined;
      if (generation && typeof generation === 'object') {
        for (const key of Object.keys(generation)) {
          expect(
            allowedGenerationKeys.has(key),
            `entry ${String(entry.id)} generation has key "${key}"`,
          ).toBe(true);
        }
      }
      for (const commitField of ['introducedBy', 'modifiedBy'] as const) {
        const value = entry[commitField];
        const list = Array.isArray(value) ? value : value === undefined ? [] : [value];
        for (const commit of list) {
          if (commit && typeof commit === 'object') {
            for (const key of Object.keys(commit as Record<string, unknown>)) {
              expect(
                allowedCommitKeys.has(key),
                `entry ${String(entry.id)} ${commitField} has key "${key}"`,
              ).toBe(true);
            }
          }
        }
      }
      const notApplicable = entry.sourceUrlNotApplicable as Record<string, unknown> | undefined;
      if (notApplicable && typeof notApplicable === 'object') {
        for (const key of Object.keys(notApplicable)) {
          expect(
            allowedSourceUrlKeys.has(key),
            `entry ${String(entry.id)} sourceUrlNotApplicable has key "${key}"`,
          ).toBe(true);
        }
      }
    }
  });

  it('holds nothing shaped like a subject, a note, a room, an account, or a request', () => {
    // A vocabulary check cannot see a learner name typed into a `title` field, so
    // the values are scanned as well. The scan is restricted to the fields that
    // are *facts about an asset* rather than authored prose: `role`, `notes`,
    // `reason`, `recipe`, the `policy` block, and the per-theme descriptions are
    // descriptions this repository writes about itself, and they legitimately name
    // game concepts. A `sha256`, a `path`, an asset `id`, a `creator`, a
    // `sourceUrl`, a `date`, and a `commit` have no business holding anything but
    // the fact they name, so those are the fields the scan covers.
    const factFields = [
      'id', 'path', 'title', 'license', 'licenseUrl', 'licenseVerified', 'creator',
      'source', 'sourceUrl', 'date', 'dateKind', 'classification', 'media',
      'legacyRenderer', 'retention', 'checksumPolicy',
    ];
    const forbiddenValue = [
      /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/, // an address
      /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i, // a UUID
      /\bBearer\s+[A-Za-z0-9._-]+/, // a credential
      /\b(lorem ipsum)\b/i,
      /\b(password|secret|api[_-]?key|auth[_-]?token)\b/i,
      // Identity vocabulary. Deliberately not the bare word "token": this file's
      // own vocabulary is design tokens, and a pattern that matched it would be a
      // test that could only be satisfied by renaming the system.
      /\b(learner|student|username|nickname|guardian|parent email)\b/i,
    ];
    // `sha256` is a closed hex format, checked separately and exactly, because a
    // pattern scan of it would be theatre.
    const hex64 = /^[0-9a-f]{64}$/;

    for (const entry of entries) {
      for (const field of factFields) {
        const value = entry[field];
        if (typeof value !== 'string' || value.length === 0) continue;
        for (const pattern of forbiddenValue) {
          expect(
            pattern.test(value),
            `entry ${String(entry.id)} field ${field}: ${value.slice(0, 120)}`,
          ).toBe(false);
        }
      }
      if (typeof entry.sha256 === 'string') {
        expect(entry.sha256, `entry ${String(entry.id)} sha256`).toMatch(hex64);
      }
      // Commit facts: a short sha, or null for a generated file, and nothing else.
      for (const commitField of ['introducedBy'] as const) {
        const value = entry[commitField] as Record<string, unknown> | undefined;
        if (value && typeof value === 'object') {
          if (value.commit !== null && value.commit !== undefined) {
            expect(String(value.commit), `entry ${String(entry.id)} commit`).toMatch(
              /^[0-9a-f]{7,40}$/,
            );
          }
          if (value.date !== null && value.date !== undefined) {
            expect(String(value.date), `entry ${String(entry.id)} commit date`).toMatch(
              /^\d{4}-\d{2}-\d{2}$/,
            );
          }
          for (const pattern of forbiddenValue) {
            expect(
              pattern.test(String(value.subject ?? '')),
              `entry ${String(entry.id)} ${commitField}.subject`,
            ).toBe(false);
          }
        }
      }
    }
    // And the whole document: no address, no UUID, and no credential anywhere,
    // including the prose, because those three cannot appear in prose either.
    const serialised = JSON.stringify(registry);
    expect(serialised, 'the registry contains an email-shaped value').not.toMatch(
      /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/,
    );
    expect(serialised, 'the registry contains a UUID').not.toMatch(
      /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i,
    );
    expect(serialised, 'the registry contains a credential').not.toMatch(/\bBearer\s+/);
  });

  it('every path is a repository-relative asset path, so no absolute host is published', () => {
    for (const entry of entries) {
      const assetPath = String(entry.path);
      expect(assetPath.startsWith('public/assets/'), assetPath).toBe(true);
      expect(assetPath.startsWith('/'), assetPath).toBe(false);
      expect(assetPath).not.toContain('..');
      expect(assetPath).not.toMatch(/^[A-Za-z]:/);
    }
  });
});

/* ========================================================================== */
/* 4. The shipped artifact carries no remote font and no remote origin.        */
/* ========================================================================== */

const REMOTE_FONT_HOST_PATTERN = /fonts\.(?:googleapis|gstatic)\.com/i;

describe('neither the generated Cozy stylesheet nor the build declares a remote font', () => {
  it('the checked-in Cozy stylesheets declare no @font-face and no remote URL', () => {
    for (const file of [COZY_TOKENS_CSS, COZY_CSS]) {
      const source = readFileSync(file, 'utf8');
      expect(source, file).not.toContain('@font-face');
      expect(source, file).not.toMatch(/@import\s+url\(/);
      expect(source, file).not.toMatch(REMOTE_FONT_HOST_PATTERN);
      // No remote anything: the generated layer is the one place a future token
      // could reintroduce a third-party origin, because it is checked in rather
      // than produced by a dependency.
      expect(source, file).not.toMatch(/https?:\/\/(?!creativecommons\.org|github\.com)/);
    }
  });

  it('the build contains no @font-face, no bundled font binary, and no font host', () => {
    if (!existsSync(DIST)) {
      // The unit suite must not depend on a build having happened. The E2E suite
      // and `npm run check:budget:welcome` are the places this is measured against
      // a real artifact; here it is only asserted when one is present.
      expect(true, 'no dist/ present; the artifact assertions are skipped').toBe(true);
      return;
    }
    const files: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else files.push(full);
      }
    };
    walk(DIST);
    expect(files.length, 'dist/ is empty; the build assertions would be vacuous').toBeGreaterThan(10);

    const fontBinary = /\.(?:woff2?|ttf|otf|eot)$/i;
    for (const file of files) {
      expect(path.basename(file), `${file} is a bundled font binary`).not.toMatch(fontBinary);
      if (!/\.(?:js|mjs|css|html|json)$/i.test(file)) continue;
      const source = readFileSync(file, 'utf8');
      expect(source, file).not.toContain('@font-face');
      expect(source, file).not.toMatch(REMOTE_FONT_HOST_PATTERN);
    }
  });

  it('the entry document names no remote origin at all', () => {
    const indexPath = path.join(DIST, 'index.html');
    if (!existsSync(indexPath)) return;
    const html = readFileSync(indexPath, 'utf8');
    // Every src/href a built document carries is either relative or a data/blob
    // URL. A remote one would be a runtime fetch the budget gate cannot see.
    const references = [...html.matchAll(/\b(?:src|href)="([^"]+)"/g)].map((match) => match[1]);
    expect(references.length, 'the built entry document has no asset references').toBeGreaterThan(0);
    for (const reference of references) {
      if (reference.startsWith('#')) continue;
      expect(reference, `${reference} is a remote reference`).not.toMatch(/^(?:[a-z][a-z0-9+.-]*:)?\/\//i);
    }
  });
});

/* ========================================================================== */
/* 5. The rollback is a rollback.                                              */
/* ========================================================================== */

/**
 * The four legacy theme blocks as they were before Phase 8, read from a committed
 * fixture.
 *
 * Deliberately *not* read from the checkout's own history, which is the defect this
 * replaces. `git show HEAD:src/styles.css` is only the pre-Phase-8 file while
 * `HEAD` still predates the change: the moment the change is committed, `HEAD` *is*
 * the new stylesheet, the gate compares the file against itself, and it finds zero
 * differences where the exit criterion requires exactly three. That is how a gate
 * passes in the author's working tree and fails in a checkout of the committed state
 * - the same defect class Phase 7 recorded twice, once as a `git show` against a sha
 * an `actions/checkout@v4` depth-1 clone does not have.
 *
 * The fixture follows `tests/phase7/support/fixtures/`: a header recording where the
 * bytes came from, a sentinel, and a digest of its own body that is re-derived on
 * every read. So the baseline cannot drift into agreeing with whatever the working
 * tree currently is, and no assertion here depends on clone depth, on a sha staying
 * resolvable, or on where the checkout lives.
 */
const BASELINE_PATH = path.join(
  REPO_ROOT,
  'tests',
  'phase8',
  'support',
  'fixtures',
  'pre-phase8-legacy-theme-blocks.css.fixture',
);
const BASELINE_SENTINEL = '/* __P8_LEGACY_THEME_BODY_BELOW__ */';

const ROOT_SELECTOR = ':root {';
const LIGHT_SELECTOR = ".ui-skin[data-theme='light'] {";
const COLORFUL_SELECTOR = ".ui-skin[data-theme='colorful'] {";
const AURORA_SELECTOR = ".ui-skin[data-theme='aurora'] {";
const LEGACY_SELECTORS = [ROOT_SELECTOR, LIGHT_SELECTOR, COLORFUL_SELECTOR, AURORA_SELECTOR];

/**
 * The two `font-family` declarations Phase 8 was permitted to change below the theme
 * blocks, and what they were.
 *
 * Named rather than pattern-matched: a "the only changed lines are font lines"
 * assertion is satisfiable by a change that is a font line, so the *values* are pinned
 * and the substituted result is checked against a digest of the pre-Phase-8 region.
 */
const LEGACY_WEB_MONO_STACK = "  font-family: 'JetBrains Mono', ui-monospace, monospace;";
const LEGACY_LOCAL_MONO_STACK =
  "  font-family: ui-monospace, 'Cascadia Code', 'SFMono-Regular', Menlo, Consolas, 'DejaVu Sans Mono', monospace;";
const LEGACY_LOCAL_MONO_STACK_LINES = 2;

/**
 * The pre-Phase-8 `src/styles.css` from the closing `}` of the last theme block to the
 * end of the file, pinned by digest and by length.
 *
 * Storing a second copy of these 5,813 lines in a fixture would make every future
 * stylesheet edit a 5,800-line diff in `tests/` rather than a one-line reviewed
 * decision, and the digest enforces the same property. The assertion does not compare
 * against a frozen copy of today: it reverts the two permitted font lines and requires
 * the result to hash to the *pre-Phase-8* digest, which is the "nothing else changed"
 * claim stated rather than frozen.
 */
const LEGACY_TAIL_SHA256 = '25d19351afcefc78e16f7487b33cf9c639e6ff732f1dfe8543bab4ceeb109145';
const LEGACY_TAIL_LINES = 5813;
const LEGACY_TAIL_BYTES = 125_252;

/**
 * Unique custom properties the whole stylesheet declares, excluding the font stacks.
 *
 * Subsumed by the block comparison and the tail digest, and kept because a red run
 * should say how many legacy declarations are in play.
 */
const LEGACY_PROPERTY_COUNT = 32;

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** `[firstLineIndex, closingBraceLineIndex]`, or `null` when the selector is absent. */
function blockBounds(source: string, selector: string): [number, number] | null {
  const lines = source.split('\n');
  const index = lines.findIndex((line) => line.trim() === selector);
  if (index === -1) return null;
  let end = index + 1;
  while (end < lines.length && lines[end].trim() !== '}') end += 1;
  if (end === lines.length) return null;
  return [index, end];
}

function blockRange(source: string, selector: string): string | null {
  const bounds = blockBounds(source, selector);
  if (bounds === null) return null;
  return source.split('\n').slice(bounds[0], bounds[1] + 1).join('\n');
}

/** Everything after the last theme block: the region the tail digest covers. */
function legacyTail(source: string, what: string): string {
  const bounds = blockBounds(source, AURORA_SELECTOR);
  if (bounds === null) throw new Error(`${what} has no ${AURORA_SELECTOR} block`);
  return source.split('\n').slice(bounds[1] + 1).join('\n');
}

interface BaselineFixture {
  header: string;
  body: string;
  measuredSha256: string;
  measuredBytes: number;
  declaredSha256: string;
  declaredBytes: number;
  declaredPath: string;
  declaredCommit: string;
  declaredShortCommit: string;
}

/**
 * Reads the baseline fixture and re-derives its digest.
 *
 * Throws rather than returning a partial fixture: a reader that quietly handed back a
 * degraded baseline would let a corrupted snapshot pass the byte-identity comparison,
 * which is the one thing the fixture exists to prevent.
 */
function readBaselineFixture(): BaselineFixture {
  const raw = readFileSync(BASELINE_PATH, 'utf8');
  const marker = raw.indexOf(BASELINE_SENTINEL);
  if (marker < 0) throw new Error(`${BASELINE_PATH} has no ${BASELINE_SENTINEL} line`);
  const split = raw.indexOf('\n', marker);
  if (split < 0) throw new Error(`${BASELINE_PATH} ends at its sentinel line and has no body`);
  const header = raw.slice(0, split);
  const body = raw.slice(split + 1);
  const declaration = (pattern: RegExp, what: string): RegExpExecArray => {
    const match = pattern.exec(header);
    if (match === null) {
      throw new Error(`${BASELINE_PATH} has no "${what}" declaration in its header`);
    }
    return match;
  };
  return {
    header,
    body,
    measuredSha256: sha256(body),
    measuredBytes: Buffer.byteLength(body, 'utf8'),
    declaredSha256: declaration(
      /^\s*\*\s+Captured as\s+:\s+\d+\s+bytes,\s+sha256\s+([0-9a-f]{64})\s*$/m,
      'Captured as',
    )[1] as string,
    declaredBytes: Number.parseInt(
      declaration(/^\s*\*\s+Captured as\s+:\s+(\d+)\s+bytes\b/m, 'Captured as')[1] as string,
      10,
    ),
    declaredPath: declaration(/^\s*\*\s+Source path\s+:\s+(\S+)\s*$/m, 'Source path')[1] as string,
    declaredCommit: declaration(
      /^\s*\*\s+Taken from\s+:\s+commit\s+([0-9a-f]{40})\b[^\n]*\bshort form\s+([0-9a-f]{7,40})\b/m,
      'Taken from',
    )[1] as string,
    declaredShortCommit: declaration(
      /^\s*\*\s+Taken from\s+:\s+commit\s+([0-9a-f]{40})\b[^\n]*\bshort form\s+([0-9a-f]{7,40})\b/m,
      'Taken from',
    )[2] as string,
  };
}

describe('rolling VITE_COZY_VISUALS back leaves the legacy themes byte-identical', () => {
  const baseline = readBaselineFixture();
  const after = readFileSync(STYLES_PATH, 'utf8');
  const tail = legacyTail(after, STYLES_PATH);

  it('the baseline is a self-verifying fixture, so it cannot be edited into agreeing with the tree', () => {
    // Three things have to be true of the "before" or nothing below it means anything:
    // the fixture's bytes are the ones its header declares, the header says where they
    // came from, and the bytes are genuinely pre-Phase-8 rather than a copy of today.
    expect(baseline.measuredSha256, 'the baseline body no longer hashes to its declared digest').toBe(
      baseline.declaredSha256,
    );
    expect(baseline.measuredBytes).toBe(baseline.declaredBytes);
    expect(baseline.declaredPath).toBe('src/styles.css');
    expect(baseline.declaredCommit).toMatch(/^[0-9a-f]{40}$/);
    expect(baseline.declaredCommit.startsWith(baseline.declaredShortCommit)).toBe(true);
    // A fixture regenerated from the working tree would satisfy every comparison below
    // while asserting nothing, and this is the line that says so.
    for (const webFont of ["'Cinzel'", "'JetBrains Mono'", "'Inter'"]) {
      expect(baseline.body, `the baseline is missing ${webFont}, so it is not the pre-Phase-8 file`).toContain(
        webFont,
      );
    }
    expect(after, 'the working stylesheet still names a web font in a theme block').not.toMatch(
      /'Cinzel'|'JetBrains Mono'|'Inter'/,
    );
  });

  it('the baseline holds exactly the four theme blocks and nothing else', () => {
    // The point of the fixture is to be a minimal, reviewable "before". A block added
    // to it would widen what "unchanged" is measured against without anyone reading it.
    const openers = baseline.body
      .split('\n')
      .filter((line) => line.trimEnd().endsWith('{'))
      .map((line) => line.trim());
    expect(openers).toEqual(LEGACY_SELECTORS);
    expect(baseline.body.split('\n').filter((line) => line.trim() === '}')).toHaveLength(4);
  });

  it.each([LIGHT_SELECTOR, COLORFUL_SELECTOR, AURORA_SELECTOR])(
    '%s is byte-identical to its pre-Phase-8 value',
    (selector) => {
      expect(blockRange(after, selector), `${selector} is missing`).toBe(
        blockRange(baseline.body, selector),
      );
    },
  );

  it('the only change in :root is the three font-stack lines the criterion requires', () => {
    const was = blockRange(baseline.body, ROOT_SELECTOR);
    const now = blockRange(after, ROOT_SELECTOR);
    expect(was, ':root is missing from the baseline').not.toBeNull();
    expect(now, ':root is missing').not.toBeNull();

    const wasLines = (was as string).split('\n');
    const nowLines = (now as string).split('\n');
    expect(nowLines, ':root changed length').toHaveLength(wasLines.length);

    const changed: string[] = [];
    for (let index = 0; index < wasLines.length; index += 1) {
      if (wasLines[index] !== nowLines[index]) changed.push(wasLines[index]);
    }
    // Every legacy colour token in :root has to be exactly as it was. The
    // criterion that requires the change is the no-remote-font one, and the
    // remote font is the only thing in :root that has to go.
    expect(changed, 'a non-font declaration in :root changed').toHaveLength(3);
    for (const line of changed) {
      expect(line).toMatch(/^\s*--?font-[a-z]+:|^\s*font-family:/);
    }
    const removed = changed.map((line) => /:\s*(.+);\s*$/.exec(line)?.[1] ?? '').join(' | ');
    const added = (now as string)
      .split('\n')
      .filter((line, index) => wasLines[index] !== line)
      .map((line) => /:\s*(.+);\s*$/.exec(line)?.[1] ?? '')
      .join(' | ');
    // None of the three may retain a web font, which is the whole point.
    for (const family of [added]) {
      expect(family).not.toMatch(/Cinzel|JetBrains|(^|,\s*)'Inter'/);
      expect(family).not.toMatch(/https?:/);
    }
    expect(removed.length).toBeGreaterThan(0);
  });

  it('no legacy colour value anywhere in the stylesheet changed', () => {
    // A belt-and-braces pass over every custom property declared in the four
    // legacy blocks, so a value edited outside :root cannot pass unnoticed.
    const declarations = (source: string): Map<string, string> => {
      const map = new Map<string, string>();
      for (const line of source.split('\n')) {
        const match = /^\s*(--[a-z0-9-]+):\s*(.+);\s*$/.exec(line);
        if (match && !/^--font|^font-family/.test(match[1])) map.set(match[1], match[2]);
      }
      return map;
    };
    const baselineDeclarations = declarations(baseline.body);
    const nowDeclarations = declarations(after);
    for (const selector of LEGACY_SELECTORS) {
      const wasBlock = declarations(blockRange(baseline.body, selector) ?? '');
      const nowBlock = declarations(blockRange(after, selector) ?? '');
      expect([...nowBlock.keys()].sort(), `${selector} lost a declaration`).toEqual(
        [...wasBlock.keys()].sort(),
      );
      for (const [property, value] of wasBlock) {
        expect(nowBlock.get(property), `${selector} ${property}`).toBe(value);
      }
    }
    // The whole stylesheet still declares the legacy palette, so a "no change"
    // reading cannot come from a file that stopped declaring it.
    expect(baselineDeclarations.size).toBe(LEGACY_PROPERTY_COUNT);
    expect(nowDeclarations.size).toBe(LEGACY_PROPERTY_COUNT);
  });

  it('below the theme blocks, only the two web font-family lines changed', () => {
    // The 5,813 remaining lines, checked as the claim rather than as a frozen copy of
    // today: put the two web-font declarations back and the result must be the
    // pre-Phase-8 region, byte for byte. A colour edited anywhere below the theme
    // blocks, an added line, a reordered rule - all of them change the digest.
    const reverted = tail.split(LEGACY_LOCAL_MONO_STACK).join(LEGACY_WEB_MONO_STACK);
    expect(tail.split('\n').filter((line) => line === LEGACY_LOCAL_MONO_STACK)).toHaveLength(
      LEGACY_LOCAL_MONO_STACK_LINES,
    );
    expect(reverted, 'the permitted font replacement did not apply').not.toBe(tail);
    expect(tail.split('\n'), 'the stylesheet gained or lost lines below the theme blocks').toHaveLength(
      LEGACY_TAIL_LINES,
    );
    expect(Buffer.byteLength(reverted, 'utf8'), 'the region changed length').toBe(LEGACY_TAIL_BYTES);
    expect(
      sha256(reverted),
      'a declaration below the theme blocks changed other than the two web font-family lines',
    ).toBe(LEGACY_TAIL_SHA256);
    // And the no-remote-font criterion holds down there too, not only in :root.
    expect(tail).not.toMatch(/Cinzel|JetBrains|(^|[^\w-])'Inter'|fonts\.(googleapis|gstatic)|@font-face/);
  });

  it('the pre-Phase-8 Google Fonts import is gone and nothing remote replaced it', () => {
    // The region the block comparison and the tail digest leave least covered: the
    // prologue above :root, where the pre-Phase-8 file had the Google Fonts comment
    // and its `@import url(...)`. Phase 8 replaced that pair with its own header and
    // two local imports. The whole stylesheet is scanned as well, comments excluded,
    // so the claim is "no active remote origin anywhere in the file" rather than
    // "the two imports at the top look local".
    const before = blockBounds(after, ROOT_SELECTOR);
    expect(before, ':root is missing').not.toBeNull();
    const prologue = after.split('\n').slice(0, (before as [number, number])[0]).join('\n');
    const imports = prologue
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('@import'));
    expect(imports, 'the prologue has no imports at all').toHaveLength(2);
    for (const statement of imports) {
      expect(statement).toMatch(/^@import\s+'\.\//);
      expect(statement).not.toMatch(/url\(|https?:|\/\//);
    }
    const active = after.replace(/\/\*[\s\S]*?\*\//g, '');
    for (const forbidden of [
      /@font-face/,
      /\burl\(/,
      /\bhttps?:\/\//,
      /fonts\.(googleapis|gstatic)/,
      /'Cinzel'/,
      /'JetBrains Mono'/,
      /'Inter'/,
    ]) {
      expect(active, `src/styles.css still contains ${forbidden}`).not.toMatch(forbidden);
    }
  });
});

/* ========================================================================== */
/* 6. The recorded media-extension set is pinned.                              */
/* ========================================================================== */

describe('the media-extension set that makes the CC0 rule mechanical is pinned', () => {
  const declared = (() => {
    const block = /const MEDIA_EXTENSIONS = new Set\(\[([\s\S]*?)\]\);/.exec(cc0CheckerSource);
    expect(block, 'the checker has no MEDIA_EXTENSIONS set').not.toBeNull();
    return [...(block?.[1] ?? '').matchAll(/'([a-z0-9]+)'/g)].map((match) => match[1]).sort();
  })();

  it('covers the raster, vector, audio, video, and font formats this project could ship', () => {
    // The set is what decides whether a dropped file is caught as media at all,
    // so the formats that matter are pinned rather than left to the next edit.
    for (const extension of [
      'svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'bmp', 'ico', 'tif', 'tiff',
      'mp3', 'ogg', 'wav', 'm4a', 'weba', 'flac',
      'mp4', 'webm', 'ogv',
      'woff', 'woff2', 'ttf', 'otf', 'eot',
    ]) {
      expect(declared, `${extension} is no longer treated as media`).toContain(extension);
    }
  });

  it('is exactly the set the shipped assets need, and nothing more', () => {
    // No entry is dead weight: every declared extension has to be a format the
    // repository could plausibly receive, which today means the ones the plan's
    // 10.3 list names plus the formats already present in the assets tree.
    const onDisk = new Set<string>();
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else {
          const extension = path.extname(entry.name).replace('.', '').toLowerCase();
          if (extension) onDisk.add(extension);
        }
      }
    };
    walk(path.join(REPO_ROOT, 'public', 'assets'));
    for (const extension of onDisk) {
      if (['json', 'md', 'txt'].includes(extension)) continue;
      expect(declared, `.${extension} exists in the tree but is not treated as media`).toContain(
        extension,
      );
    }
    // 25: 11 raster/vector, 6 audio, 3 video, 5 font. Asserted as a number so a
    // silent addition - the exact shape of a future hole - shows up as a diff
    // rather than as a passing test.
    expect(declared.length).toBe(25);
  });
});

/* ========================================================================== */
/* 7. The Cozy placeholders are genuinely procedural.                         */
/* ========================================================================== */

describe('the six Cozy placeholders are reproducible from the committed generator', () => {
  function generate(root: string): void {
    execFileSync(process.execPath, [path.join(root, 'scripts', 'generate-cozy-placeholders.mjs')], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  }

  it('regenerating produces byte-identical files, so the pinned checksums mean something', () => {
    const root = scratch('gen');
    mkdirSync(path.join(root, 'scripts'), { recursive: true });
    mkdirSync(path.join(root, 'public', 'assets'), { recursive: true });
    cpSync(GENERATOR_PATH, path.join(root, 'scripts', 'generate-cozy-placeholders.mjs'));
    cpSync(REGISTRY_PATH, path.join(root, 'public', 'assets', 'asset-licenses.json'));
    generate(root);

    const committed = readdirSync(COZY_DIR).filter((name) => name.endsWith('.svg')).sort();
    expect(committed, 'the placeholder set is not six files').toHaveLength(6);
    const generated = readdirSync(path.join(root, 'public', 'assets', 'cozy')).sort();
    expect(generated).toEqual(committed);
    for (const name of committed) {
      expect(
        readFileSync(path.join(root, 'public', 'assets', 'cozy', name)).equals(
          readFileSync(path.join(COZY_DIR, name)),
        ),
        `${name} does not match the committed bytes`,
      ).toBe(true);
    }
  });

  it('the generator is deterministic across runs, so a checksum cannot drift', () => {
    const root = scratch('gen2');
    mkdirSync(path.join(root, 'scripts'), { recursive: true });
    mkdirSync(path.join(root, 'public', 'assets'), { recursive: true });
    cpSync(GENERATOR_PATH, path.join(root, 'scripts', 'generate-cozy-placeholders.mjs'));
    cpSync(REGISTRY_PATH, path.join(root, 'public', 'assets', 'asset-licenses.json'));
    generate(root);
    const first = readFileSync(path.join(root, 'public', 'assets', 'cozy', 'cozy-ink-panel.svg'));
    generate(root);
    const second = readFileSync(path.join(root, 'public', 'assets', 'cozy', 'cozy-ink-panel.svg'));
    expect(second.equals(first), 'a second run produced different bytes').toBe(true);
    // No timestamp: a generatedAt field would make every run a checksum mismatch,
    // which is exactly the failure the sprite manifest documents having to work
    // around with a semantic check instead.
    expect(GENERATOR_PATH.endsWith('.mjs')).toBe(true);
    const generatedSource = readFileSync(
      path.join(root, 'public', 'assets', 'cozy', 'cozy-ink-panel.svg'),
      'utf8',
    );
    expect(generatedSource).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
  });

  it('each placeholder carries its own id and recipe, and no animation', () => {
    // The registry's `embedMarker` promise is that the generated bytes name the
    // entry, and the reduced-motion promise is that the art is inert. Both are
    // checkable from the committed file, so both are checked here.
    const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')) as Registry;
    const placeholders = (registry.assets ?? []).filter(
      (entry) => typeof entry.path === 'string' && entry.path.startsWith('public/assets/cozy/'),
    );
    expect(placeholders).toHaveLength(6);
    for (const entry of placeholders) {
      const generation = entry.generation as Record<string, unknown> | undefined;
      expect(generation?.embedMarker, String(entry.id)).toBe(true);
      const source = readFileSync(path.join(REPO_ROOT, String(entry.path)), 'utf8');
      const head = source.slice(0, 2000);
      expect(head, String(entry.id)).toContain(`id: ${String(entry.id)}`);
      expect(head, String(entry.id)).toContain(`recipe: ${String(generation?.recipe)}`);
      expect(source, `${String(entry.path)} animates`).not.toMatch(/<animate|<set\b|@keyframes/);
      expect(source, `${String(entry.path)} styles`).not.toMatch(/<style|animation:/);
    }
  });

  it('CREDITS.md names every registered path and nothing it does not', () => {
    // The credits page is the human-readable face of the registry; a path in one
    // and not the other is a drift a reader would trust the wrong side of.
    const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')) as Registry;
    const credits = readFileSync(CREDITS_PATH, 'utf8');
    const mentioned = new Set(
      [...credits.matchAll(/`(public\/assets\/[^`\s]+)`/g)].map((match) => match[1]),
    );
    const registered = new Set(
      (registry.assets ?? []).map((entry) => String(entry.path)),
    );
    expect(mentioned.size).toBe(registered.size);
    for (const assetPath of registered) expect(mentioned, assetPath).toContain(assetPath);
  });
});

/*
 * Closed since the Phase 8 QA pass: the gap this block used to document is closed
 * ---------------------------------------------------------------------------
 * This file's `MEDIA_EXTENSIONS` assertion pins the 25 extensions the checker treats
 * as media, and that count is unchanged. What changed is that the set is no longer the
 * only thing holding the rule together.
 *
 * The gap, as recorded then: an extension outside that set could be registered with
 * `media: false` and pass the gate, which is not the same as not being media. The QA
 * pass registered `.svgz`, `.aac`, `.oga`, `.opus`, `.apng`, `.jfif`, `.pjpeg`, `.glb`,
 * `.ktx2`, `.hdr`, `.exr`, `.dds`, `.basis`, `.wav2`, `.md`, and `.obj` as
 * `repository-authored` non-media and the gate exited 0 sixteen times, and an
 * unregistered one of those failed as `E-UNREGISTERED-FILE` rather than
 * `E-UNREGISTERED-MEDIA`. Both statements are now false.
 *
 * The extension vocabulary is closed instead. An extension is in `MEDIA_EXTENSIONS`, in
 * the declared `NON_MEDIA_EXTENSIONS` set, or unclassified - and unclassified is a
 * failure in every direction that can reach the build:
 *
 * - A registry entry with an unclassified extension is refused as
 *   `E-UNKNOWN-EXTENSION`, so `media: false` can no longer be asserted about a suffix
 *   there is nothing to check it against.
 * - An unregistered unclassified file under `public/assets/` is refused as
 *   `E-UNREGISTERED-MEDIA`, not `E-UNREGISTERED-FILE`: Vite copies `public/` into the
 *   build verbatim, so an unclassified file there ships whatever it is.
 * - A module under `src/` that names an unclassified extension is refused as
 *   `E-UNREGISTERED-SOURCE-MEDIA`, because the bundler resolves `./icon.svgz` exactly
 *   as it resolves `./icon.png`.
 * - The extension is not the only evidence. A `media: false` file whose bytes open with
 *   a known media container signature is refused as `E-MEDIA-SIGNATURE`, so a real
 *   image renamed `.md` is caught by the bytes even when the suffix is legal.
 *
 * The one deliberate exception, so it is not mistaken for a hole: a file under `src/`
 * that no module names and whose extension is unclassified is *skipped* rather than
 * refused. Vite emits a source-root file only when the module graph reaches it, so such
 * a file cannot ship; it is skipped only after its bytes have been checked against the
 * same media signatures, and the count of skipped files is printed in the gate's
 * summary so a skip is on the record rather than invisible. A file nothing reaches is
 * not a licensing problem; a file the build emits is.
 *
 * Owned and asserted elsewhere: `cc0-media-extension-vocabulary.test.ts` owns the
 * vocabulary and the byte check, and `cc0-source-media-scope.test.ts` owns the
 * source-tree reachability rule. This file keeps the count pin, which is the part that
 * does not need a policy to state.
 */
